travelItenerary/iteneraryApplication/urls.py
from django.conf.urls import url 
from . import views


urlpatterns = [
	# url(r'^/city/add/$', views.add_city, name='add_city'),                     #views.add_city is the function which handles the call and name is used to refer the url elsewhere so that it is not hardcoded
	url(r'^form/$', views.itenerary_form, name='itenerary_form'),
	url(r'^thanks/$', views.thanks, name="thanks"),
	url(r'^show_plan/$', views.show_plan, name="show_plan"),
	url(r'^map/$', views.show_map, name="show_map"),
]

travelItenerary/travelItenerary/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^iteneraryApplication/', include('iteneraryApplication.urls')),
    url(r'^admin/', admin.site.urls),
    
]

travelItenerary/iteneraryApplication/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import uuid
from datetime import date
from django.utils.translation import gettext as _

class City(models.Model):
	city_name = models.CharField(max_length=40, primary_key=True)

	def __str__(self):
		return '%s' % self.city_name


class Type(models.Model):
	type_name = models.CharField(max_length=20, primary_key=True)

	def __str__(self):
		return '%s' % self.type_name.replace("_", " ")

class PointOfInterest(models.Model):
	POI_id = models.TextField(primary_key=True)
	POI_image_src = models.URLField()
	POI_name = models.CharField(max_length=40)
	formatted_address = models.TextField()
	formatted_phoneNo = models.CharField(max_length=15)
	latitude = models.DecimalField( max_digits=5, decimal_places=2)
	longitude = models.DecimalField( max_digits=5, decimal_places=2)
	no_people_who_rated = models.IntegerField(default = 1)
	rating = models.DecimalField(max_digits = 2, decimal_places = 1)
	POI_map_url = models.URLField()
	POI_website_url = models.URLField()
	types = models.ManyToManyField(Type,null=True,blank=True)
	POI_city = models.ForeignKey(City,on_delete=models.CASCADE, verbose_name = "point of interest of the corresponding city",null=True,blank=True)
	average_time_spent = models.DecimalField(max_digits=4, decimal_places=2, default=0)
	description = models.TextField()

	def __str__(self):
		return '%s' % self.POI_name

class OpenCloseTime(models.Model):
	open_time = models.IntegerField()
	close_time = models.IntegerField()
	day = models.IntegerField()
	POI = models.ForeignKey(PointOfInterest, on_delete=models.CASCADE, verbose_name="the opening and closing time of the corresponding point of interest on a certain day",null=True,blank=True)


class Photo(models.Model):
	photo_id = models.TextField(primary_key=True)
	height = models.IntegerField()
	width = models.IntegerField()
	photo_src = models.URLField()
	POI = models.ForeignKey(PointOfInterest,on_delete=models.CASCADE, verbose_name="photo of corresponding point of interest",null=True,blank=True)

class Form(models.Model):
	city = models.ForeignKey(
        City,
        on_delete=models.CASCADE,
    )
	start_date = models.DateField(_("Start Date"), default=date.today)
	end_date = models.DateField(_("End Date"), default=date.today)
	type_tags = models.ManyToManyField(Type,null=True,blank=True)

class DistanceTime(models.Model):
	source = models.ForeignKey(PointOfInterest, on_delete=models.CASCADE, related_name = "source_set",null=True,blank=True)
	dest = models.ForeignKey(PointOfInterest, on_delete=models.CASCADE, related_name = "dest_set",null=True,blank=True)
	distance = models.DecimalField(max_digits=15, decimal_places = 2)
	time = models.IntegerField()



# Create your models here.

travelItenerary/iteneraryApplication/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,HttpResponse, HttpResponseRedirect
from django.template import loader
from .iteneraryform import IteneraryForm
import json
from .itenerary_generator import generate_itenerary
from models import *
import os, copy
from django.conf import settings

plan = {}
# Create your views here.
# plan = {
#     "city": "Dubai",
#     "start_date": "08/21/2018",
#     "days": 2,
#     "tour":[
#                 [
#                     {
#                         "lat": 25.242992, 
#                         "lng": 55.33269 ,
#                         "name": "Park Hyatt Dubai", 
#                         "place_id": "ChIJ90SK0zxdXz4REVAnXhulhJQ", 
#                         "rating": 5,
#                         "description": "Lorem ipsum dictumst habitant hendrerit massa nostra fermentum feugiat",
#                         "time": "time_to_visit",
#                         "cost": "cost"
#                     },
#                     {
#                         "lat": 25.197405, 
#                         "lng": 55.274331 ,
#                         "name" : "At the top of burj khalifa",
#                         "place_id": "ChIJK_3sryxoXz4Ra2EynnqG6UQ", 
#                         "rating": 3,
#                         "description": "Lorem ipsum dictumst habitant hendrerit massa nostra fermentum feugiat",
#                         "time": "time_to_visit",
#                         "cost": "cost"

#                     },
#                     {
#                         "name": "The Dubai Mall", 
#                         "lat": 25.198518, 
#                         "lng": 55.279619,
#                         "place_id": "ChIJB1zIKShoXz4RnbaTPPup7aU", 
#                         "rating": 4,
#                         "description": "Lorem ipsum dictumst habitant hendrerit massa nostra fermentum feugiat",
#                         "time": "time_to_visit",
#                         "cost": "cost"
#                     },
#                     {
#                         "lat": 25.1330986, 
#                         "lng": 55.183466 , "name": "Madinat Jumeirah",
#                         "place_id": "ChIJORSp9gBCXz4RtnTCn-ul3mo", 
#                         "rating": 4,
#                         "description": "Lorem ipsum dictumst habitant hendrerit massa nostra fermentum feugiat",
#                         "time": "time_to_visit",
#                         "cost": "cost"
#                     }
#                 ],
#                 [
#                     {
#                         "lat": 25.139409, 
#                         "lng": 55.188844 , 
#                         "name": "Wild wadi waterpark",
#                         "place_id": "ChIJh7LUHlFqXz4RbIRg-g5fo-E", 
#                         "rating": 5,
#                         "description": "Lorem ipsum dictumst habitant hendrerit massa nostra fermentum feugiat",
#                         "time": "time_to_visit",
#                         "cost": "cost"
#                     },
#                     {
#                         "lat": 25.1971411, 
#                         "lng": 55.2796665 , 
#                         "name" : "Dubai ice rink",
#                         "place_id": "ChIJ0Yv9GShoXz4R5t9gYCGvNHs", 
#                         "rating": 2,
#                         "description": "Lorem ipsum dictumst habitant hendrerit massa nostra fermentum feugiat",
#                         "time": "time_to_visit",
#                         "cost": "cost"
#                     }
#                 ]
#     ]
# }

def get_image_url(city, place_id, ct):
    return "img/data/" + city + "/sites/" + place_id + "/" + ct + ".jpeg"

def add_images_rating(given_plan):
    for day in given_plan['tour']:
        for place in day:
            place['rating_len'] = range(int(round(float(place['rating']))))
            place['images'] = []
            for i in range(0, 4):
                place['images'].append(get_image_url(given_plan['city'], place['place_id'], str(i+1)))
            place['lat'] = float(place['lat'])
            place['lng'] = float(place['lng'])
    return given_plan

def am_pm(value):
    hr = int(value)
    mn = int((value*60) % 60)
    mn = mn
    if hr > 12:
        if mn < 10: return str(hr-12) + " : 0" + str(mn) + " pm"
        else: return str(hr-12) + " : " + str(mn) + " pm"
    elif hr == 12:
        if mn < 10: return str(hr) + " : 0" + str(mn) + " pm"
        else: return str(hr) + " : " + str(mn) + " pm"
    else:
        if mn < 10: return str(hr) + " : 0" + str(mn) + " am"
        else: return str(hr) + " : " + str(mn) + " am"



def get_time_string(start, duration):
    time_string = ""
    time_string += am_pm(start + 9.00) + " to "
    time_string += am_pm(start + 9.00 + duration) 
    return time_string

def correct_time_format(given_plan):
    for day in given_plan['tour']:
        for place in day:
            time_spent = PointOfInterest.objects.get(POI_id = place['place_id']).average_time_spent
            place['time_to_show'] = get_time_string(float(place['time']), float(time_spent))
    return given_plan

def get_no_ratings(given_plan):
    for day in given_plan['tour']:
        for place in day:
            n_ratings = PointOfInterest.objects.get(POI_id = place['place_id']).no_people_who_rated
            place['no_of_ratings'] = n_ratings
    return given_plan

def get_timetravel(given_plan):
    for day in given_plan['tour']:
        first = True
        pre_id = ""
        for place in day:
            if first == True:
                first = False
                place['travel_time'] = -1
                place['travel_dist'] = -1
                pre_id = place['place_id']
                continue
            source = PointOfInterest.objects.get(POI_id = pre_id)
            dest = PointOfInterest.objects.get(POI_id = place['place_id'])
            obj = DistanceTime.objects.get(source = source, dest = dest)
            place['travel_dist'] = float(obj.distance) /1000.0
            place['travel_time'] = obj.time
            pre_id = place['place_id']
    return given_plan



def itenerary_form(request): 
    form = IteneraryForm(
        initial = {
            'city': '',
            'start_date': '',
            'end_date': ''
        }
        )
    if request.method == "POST":
        form = IteneraryForm(request.POST)
        if form.is_valid():
            form.save()
            context = dict()
            context['city']= form.cleaned_data.get("city")
            context['start_date'] = form.cleaned_data.get("start_date")
            context['end_date'] = form.cleaned_data.get("end_date")
            context['type_tags'] = form.cleaned_data.get("type_tags")
            global plan
            plan = get_timetravel(get_no_ratings(correct_time_format(add_images_rating(json.loads(generate_itenerary(context))))))
            return HttpResponseRedirect('/iteneraryApplication/show_plan/');
    
        # return render(request, 'templates/index2.html', {'form': itene})
    return render(request, 'index2.html', {'form': form})
    # return render(request, html template page to return after form, params for form)


def show_plan(request):
    #will get the plan from the algorithm
    global plan
    return HttpResponse(loader.get_template("show_plan.html").render(plan))

def thanks(request):
    return HttpResponse("Hello World")

def show_map(request):
    global plan
    tour = plan["tour"]
    return render(request , 'map.html' , {
        'plan' : json.dumps(tour),
        'start_date' : plan['start_date'], #mm/dd/yy
        'city' : plan['city']
    });

travelItenerary/iteneraryApplication/templates/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Basic Travel Itenerary Generator</title>

    <!-- daterange imports -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
  <!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script> -->
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


	<!-- Bootstrap Date-Picker Plugin --><!-- 
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/> -->

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{%static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static 'css/creative.css' %}" rel="stylesheet">
    <link href="{%static 'css/custom_style.css' %}" rel="stylesheet">

    <!-- Bootstrap core JavaScript -->
    <!-- <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script> -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <!-- <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script> -->
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <script type="text/javascript">
      $(function() {

        $( "#id_start_date" ).datepicker({
          changeMonth: true,
          changeYear: true,
          minDate: 0,
        });
        $( "#id_end_date" ).datepicker({
          changeMonth: true,
          changeYear: true,
          minDate: 0,
        });
      });
      </script>



    {% load bootstrap3 %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Itenerary Planner</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#services">Services</a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#portfolio">Portfolio</a>
            </li> -->
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>We do basic itenerary planning</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">This website allows you to create custom travel itenerary based on your preferences. On top of that, we don't store any data about you or your itenerary. So you can be assured that no one is tracking you! </p>
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Start Planning</a>
          </div>
        </div>
      </div>
    </header>

    <section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">We've got what you need!</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4">This website has everything you need to start planning your itenerary.</p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Get Started!</a>
          </div>
        </div>
      </div>
    </section>

    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">Plan your itenerary</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>

    <form style="margin: auto;  width: 50%;" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form error_types='all'%}

      {% buttons %}
        <button type="submit" class="btn btn-primary">
          {% bootstrap_icon "thumb" %} Submit
        </button>
      {% endbuttons %}
    </form>
    </section>

    <!-- <section class="p-0" id="portfolio">
      <div class="container-fluid p-0">
        <div class="row no-gutters popup-gallery">
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/1.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/1.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/2.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/2.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/3.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/3.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/4.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/4.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/5.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/5.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="img/portfolio/fullsize/6.jpg">
              <img class="img-fluid" src="img/portfolio/thumbnails/6.jpg" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Category
                  </div>
                  <div class="project-name">
                    Project Name
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section> -->

    <!-- <section class="bg-dark text-white">
      <div class="container text-center">
        <h2 class="mb-4">Free Download at Start Bootstrap!</h2>
        <a class="btn btn-light btn-xl sr-button" href="http://startbootstrap.com/template-overviews/creative/">Download Now!</a>
      </div>
    </section> -->

    <section class="bg-dark text-white" id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Let's Get In Touch!</h2>
            <hr class="my-4">
            <p class="mb-5">Want even more customisation or contact us for any further help. Drop us an email or give us a call and we will not get back to you!</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fa fa-phone fa-3x mb-3 sr-contact"></i>
            <p>123-456-6789</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
            <p>
              <a href="mailto:your-email@your-domain.com">feedback@startbootstrap.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>

   <!--  <script>
    $(function() {
      var date = $( "#id_start_date" ).datepicker({
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        minDate: 0,
      });

      $( "#id_end_date" ).datepicker({
        dateFormat: 'dd-mm-yy',
        changeMonth: true,
        changeYear: true,
        minDate: 0,
        // You can put more options here.

      });
      console.log(new Date(date))
    });
    </script> -->

    <script type="text/javascript">
      $(document).ready(function() {
        
        $('.form-group input, .form-group select').change(function() {
          updateConfig();
        })
        function updateConfig() {

          var date = $("#id_start_date").datepicker( 'getDate' );
          console.log(date);
          // $( "#id_end_date" ).datepicker({
          //   dateFormat: 'dd-mm-yy',
          //   changeMonth: true,
          //   changeYear: true,
          //   minDate: date,
          //   // You can put more options here.

          // });
          $('#id_end_date').datepicker('option', 'minDate', date);
        }
      });
      </script>
    

  </body>

</html>